import { createGlobalThemeContract } from '@vanilla-extract/css';

export const vars = createGlobalThemeContract({
  color: {
    brand: 'ds-color-brand',
    signal: 'ds-color-signal',
    highlight: 'ds-color-highlight',
    surface: 'ds-color-surface',
    contrast: 'ds-color-contrast',
    background: 'ds-color-background',
    foreground: 'ds-color-foreground',
    card: 'ds-color-card',
    cardForeground: 'ds-color-card-foreground',
    muted: 'ds-color-muted',
    mutedForeground: 'ds-color-muted-foreground',
    border: 'ds-color-border',
    input: 'ds-color-input',
    ring: 'ds-color-ring',
    primary: 'ds-color-primary',
    primaryForeground: 'ds-color-primary-foreground',
    secondary: 'ds-color-secondary',
    secondaryForeground: 'ds-color-secondary-foreground',
    accent: 'ds-color-accent',
    accentForeground: 'ds-color-accent-foreground',
    destructive: 'ds-color-destructive',
    destructiveForeground: 'ds-color-destructive-foreground',
    popover: 'ds-color-popover',
    popoverForeground: 'ds-color-popover-foreground',
  },
  typography: {
    fontFamily: {
      heading: 'ds-typography-font-family-heading',
      body: 'ds-typography-font-family-body',
    },
    fontSize: {
      display: 'ds-typography-font-size-display',
      h1: 'ds-typography-font-size-h1',
      h2: 'ds-typography-font-size-h2',
      h3: 'ds-typography-font-size-h3',
      h4: 'ds-typography-font-size-h4',
      h5: 'ds-typography-font-size-h5',
      h6: 'ds-typography-font-size-h6',
      lead: 'ds-typography-font-size-lead',
      bodyLg: 'ds-typography-font-size-body-lg',
      body: 'ds-typography-font-size-body',
      bodySm: 'ds-typography-font-size-body-sm',
      caption: 'ds-typography-font-size-caption',
      overline: 'ds-typography-font-size-overline',
    },
    lineHeight: {
      tight: 'ds-typography-line-height-tight',
      snug: 'ds-typography-line-height-snug',
      normal: 'ds-typography-line-height-normal',
      relaxed: 'ds-typography-line-height-relaxed',
    },
    fontWeight: {
      regular: 'ds-typography-font-weight-regular',
      medium: 'ds-typography-font-weight-medium',
      semibold: 'ds-typography-font-weight-semibold',
      bold: 'ds-typography-font-weight-bold',
    },
    letterSpacing: {
      tight: 'ds-typography-letter-spacing-tight',
      normal: 'ds-typography-letter-spacing-normal',
      wide: 'ds-typography-letter-spacing-wide',
      widest: 'ds-typography-letter-spacing-widest',
    },
  },
  space: {
    '0': 'ds-space-0',
    '1': 'ds-space-1',
    '2': 'ds-space-2',
    '3': 'ds-space-3',
    '4': 'ds-space-4',
    '5': 'ds-space-5',
    '6': 'ds-space-6',
    '8': 'ds-space-8',
    '10': 'ds-space-10',
    '12': 'ds-space-12',
    '16': 'ds-space-16',
    '20': 'ds-space-20',
    '24': 'ds-space-24',
  },
  radius: {
    none: 'ds-radius-none',
    sm: 'ds-radius-sm',
    md: 'ds-radius-md',
    lg: 'ds-radius-lg',
    full: 'ds-radius-full',
  },
  shadow: {
    none: 'ds-shadow-none',
    sm: 'ds-shadow-sm',
    md: 'ds-shadow-md',
  },
});
